#!/bin/sh
# Generate the consumer-facing metadata that ships inside every SDK tarball:
#
#   bin/php-config            relocatable shim (unix only)
#   THIRD-PARTY-NOTICES.txt   license summary + file inventory for the payload
#
# Run from build.yml's "Package SDK" step, on the runner host, against the
# already-staged sdk/ directory. Kept as a committed script (checked out to
# sdk-tools/ via actions/checkout with a `path:`, which touches only that
# subdirectory and leaves spc's buildroot/downloads caches alone) rather than
# a heredoc, so it is reviewable and can be run locally against an unpacked
# tarball:
#
#   tar xzf php-sdk-8.4.23-linux-x86_64-gnu.tar.gz -C /tmp/sdk
#   sh tools/mk-sdk-metadata.sh /tmp/sdk linux
#   /tmp/sdk/bin/php-config --includes
#
# POSIX sh only: this runs under dash on the Linux runners, bash-3.2 in sh
# mode on macOS, and Git-for-Windows bash on the Windows runner.

set -eu

sdk_root=${1:-}
platform=${2:-}

if [ -z "$sdk_root" ] || [ -z "$platform" ]; then
    echo "usage: mk-sdk-metadata.sh <sdk-root> <linux|macos|windows>" >&2
    exit 2
fi
case "$platform" in
    linux | macos | windows) ;;
    *)
        echo "mk-sdk-metadata.sh: unknown platform '$platform'" >&2
        exit 2
        ;;
esac
if [ ! -d "$sdk_root/lib" ] || [ ! -d "$sdk_root/include/php" ]; then
    echo "mk-sdk-metadata.sh: '$sdk_root' does not look like a staged SDK (need lib/ and include/php/)" >&2
    exit 1
fi

version_h="$sdk_root/include/php/main/php_version.h"
config_h="$sdk_root/include/php/main/php_config.h"
test -f "$version_h" || {
    echo "mk-sdk-metadata.sh: missing $version_h" >&2
    exit 1
}

php_version=$(sed -n 's/^#define PHP_VERSION "\(.*\)"/\1/p' "$version_h")
php_version_id=$(sed -n 's/^#define PHP_VERSION_ID \([0-9]*\).*/\1/p' "$version_h")
test -n "$php_version" || {
    echo "mk-sdk-metadata.sh: could not read PHP_VERSION from $version_h" >&2
    exit 1
}
test -n "$php_version_id" || {
    echo "mk-sdk-metadata.sh: could not read PHP_VERSION_ID from $version_h" >&2
    exit 1
}

# `#define ZTS 1` in php_config.h is the only in-tarball marker distinguishing
# the default thread-safe SDK from the -nts variant. Consumers key off it.
zts=0
if [ -f "$config_h" ] && [ "$(sed -n 's/^#define ZTS \([0-9]*\).*/\1/p' "$config_h" | head -n 1)" = "1" ]; then
    zts=1
fi

# ---------------------------------------------------------------------------
# bin/php-config
# ---------------------------------------------------------------------------
#
# Consumers that build against a system PHP (PAM, phpize-style build scripts)
# invoke php-config unconditionally. The tarball extracts anywhere, so the shim
# resolves its own prefix at run time instead of baking one in.
#
# Not generated on Windows: php-config is a POSIX shell script and nothing in
# the Windows toolchain consumes one.
if [ "$platform" != "windows" ]; then
    # --libs enumerates the static archives this SDK ships. Excluded:
    #   libicutest      ICU test harness, never linked by PHP
    #   libncurses++    C++ ncurses binding, never linked by PHP
    #   *_shlib         PIC duplicates of libpgcommon/libpgport
    archives=""
    for a in "$sdk_root"/lib/*.a; do
        [ -f "$a" ] || continue
        base=$(basename "$a" .a)
        case "$base" in
            libphp | libicutest | libncurses++ | *_shlib) continue ;;
        esac
        archives="$archives -l${base#lib}"
    done
    if [ "$platform" = "macos" ]; then
        # ld64 does multi-pass resolution; it has no --start-group and errors
        # on it. libc++ is the system C++ runtime ICU/intl were built against.
        libs="-lphp$archives -lc++"
    else
        # GNU ld needs an explicit group: PHP's archives are mutually
        # recursive (libphp -> libz, libcurl -> libssl, libxml2 -> libz, ...).
        libs="-Wl,--start-group -lphp$archives -Wl,--end-group -lm -ldl -lpthread"
    fi

    mkdir -p "$sdk_root/bin"
    cat > "$sdk_root/bin/php-config" <<'PHPCONFIG_HEAD'
#!/bin/sh
# php-config shim for the ephpm php-sdk tarball.
#
# This SDK is a static-php-cli --build-embed build: it ships libphp.a plus the
# static archives it was linked against, and headers. There is no PHP binary,
# no shared extension directory and no recorded configure line, so the options
# that would report those are refused rather than answered with a plausible
# lie. Everything else is resolved relative to this script, so the tarball
# stays relocatable.
#
# Generated by tools/mk-sdk-metadata.sh -- do not edit inside the tarball.

set -eu

# Resolve our own prefix, following symlinks. `readlink -f` is not portable to
# macOS, so walk the chain by hand.
self=$0
while [ -L "$self" ]; do
    link=$(readlink "$self")
    case $link in
        /*) self=$link ;;
        *) self=$(dirname "$self")/$link ;;
    esac
done
unset CDPATH
bindir=$(cd -- "$(dirname -- "$self")" && pwd -P)
prefix=$(cd -- "$bindir/.." && pwd -P)

include_dir="$prefix/include/php"

# Mirrors a stock php-config, plus -I<include_dir>/sapi so both
# <sapi/embed/php_embed.h> and <embed/php_embed.h> resolve.
includes="-I$include_dir \
-I$include_dir/main \
-I$include_dir/TSRM \
-I$include_dir/Zend \
-I$include_dir/ext \
-I$include_dir/ext/date/lib \
-I$include_dir/sapi"

PHPCONFIG_HEAD

    {
        echo "version=\"$php_version\""
        echo "vernum=\"$php_version_id\""
        echo "zts=\"$zts\""
        echo "ldflags=\"-L\$prefix/lib\""
        echo "libs=\"$libs\""
        echo ""
    } >> "$sdk_root/bin/php-config"

    cat >> "$sdk_root/bin/php-config" <<'PHPCONFIG_TAIL'
usage() {
    cat <<USAGE
Usage: php-config [OPTION]

  --prefix            SDK prefix (resolved from this script location)
  --includes          -I flags for compiling against these headers
  --include-dir       path to the PHP header root
  --ldflags           -L flags for linking against lib/
  --libs              static archives this SDK ships (see caveat below)
  --extension-dir     conventional shared-extension path under this prefix
  --version           PHP version
  --vernum            PHP version as an integer (PHP_VERSION_ID)
  --php-sapis         SAPIs in this SDK
  --help              this message

--libs enumerates what is in lib/; it is a starting point, not a verified
link line. Whole-archive and symbol-ordering decisions are the consumer's.

Refused on purpose: --php-binary and --configure-options. This SDK contains
no PHP executable and static-php-cli strips the configure line from the
build, so there is no truthful answer.

ZTS: this build reports zts=$zts. Consumers can also read
"#define ZTS 1" from include/php/main/php_config.h.
USAGE
}

case "${1:-}" in
    --prefix) echo "$prefix" ;;
    --includes) echo "$includes" ;;
    --include-dir) echo "$include_dir" ;;
    --ldflags) echo "$ldflags" ;;
    --libs) echo "$libs" ;;
    --extension-dir) echo "$prefix/lib/php/extensions" ;;
    --version) echo "$version" ;;
    --vernum) echo "$vernum" ;;
    --php-sapis) echo "embed" ;;
    --help | -h | --usage | "") usage ;;
    --php-binary)
        echo "php-config: this SDK ships no PHP executable" >&2
        exit 1
        ;;
    --configure-options)
        echo "php-config: static-php-cli does not record a configure line in this build" >&2
        exit 1
        ;;
    *)
        echo "php-config: unsupported option '$1'" >&2
        usage >&2
        exit 1
        ;;
esac
PHPCONFIG_TAIL

    chmod 0755 "$sdk_root/bin/php-config"
    echo "==> wrote $sdk_root/bin/php-config (PHP $php_version, zts=$zts)"

    # Prove the shim runs and answers before it is tarred. A shim that fails
    # at the consumer is worse than no shim at all.
    "$sdk_root/bin/php-config" --version > /dev/null
    "$sdk_root/bin/php-config" --includes > /dev/null
    "$sdk_root/bin/php-config" --libs > /dev/null
    got=$("$sdk_root/bin/php-config" --version)
    if [ "$got" != "$php_version" ]; then
        echo "mk-sdk-metadata.sh: shim reports '$got', headers say '$php_version'" >&2
        exit 1
    fi
fi

# ---------------------------------------------------------------------------
# THIRD-PARTY-NOTICES.txt
# ---------------------------------------------------------------------------
#
# The repository's MIT license covers the workflows and scripts that produce
# these tarballs. It does NOT cover what is inside them: PHP plus ~20 upstream
# libraries, each under its own terms. Say so explicitly in the payload.
#
# The component list below is the maximal set static-php-cli builds for this
# SDK's extension selection; the generated Inventory section records what this
# particular tarball actually contains.
notices="$sdk_root/THIRD-PARTY-NOTICES.txt"
cat > "$notices" <<NOTICE_HEAD
ephpm/php-sdk -- third-party notices
PHP $php_version, $platform, ZTS=$zts

SCOPE
The MIT license in the ephpm/php-sdk repository applies to the build
workflows and scripts in that repository. It does NOT apply to the contents
of this tarball. This tarball is an aggregate of PHP and its dependencies,
each distributed under its own license, listed below.

Redistributing binaries built from this SDK means redistributing these
components. Most of the licenses below require reproducing their copyright
notice and license text. The full texts are not bundled here; obtain them
from each upstream project at the URL given. This summary is for orientation
and is not legal advice.

COMPONENTS

  PHP (libphp.a / php8embed.lib)          PHP-3.01
    The Zend Engine is separately licensed under the Zend Engine License 2.00.
    https://www.php.net/license/

  OpenSSL (libssl, libcrypto)             Apache-2.0
    https://www.openssl.org/source/license.html
  ICU (libicuuc, libicui18n, libicudata, libicuio, libicutu)
                                          ICU (Unicode-DFS-2016)
    https://github.com/unicode-org/icu/blob/main/LICENSE
  libxml2                                 MIT
    https://gitlab.gnome.org/GNOME/libxml2
  libxslt / libexslt                      MIT
    https://gitlab.gnome.org/GNOME/libxslt
  oniguruma (libonig)                     BSD-2-Clause
    https://github.com/kkos/oniguruma
  SQLite (libsqlite3)                     blessing (public domain dedication)
    https://www.sqlite.org/copyright.html
  curl (libcurl)                          curl
    https://curl.se/docs/copyright.html
  zlib (libz)                             Zlib
    https://zlib.net/zlib_license.html
  bzip2 (libbz2)                          bzip2-1.0.6
    https://sourceware.org/bzip2/
  xz / liblzma                            0BSD
    https://tukaani.org/xz/
  libpng (libpng16)                       Libpng
    http://www.libpng.org/pub/png/src/libpng-LICENSE.txt
  libsodium                               ISC
    https://github.com/jedisct1/libsodium
  libzip                                  BSD-3-Clause
    https://libzip.org/license/
  PostgreSQL client (libpq, libpgcommon, libpgport)
                                          PostgreSQL
    https://www.postgresql.org/about/licence/
  GMP (libgmp)                            LGPL-3.0-or-later OR GPL-2.0-or-later
    https://gmplib.org/manual/Copying
  GNU libiconv (libiconv, libcharset)     LGPL-2.1-or-later
    https://www.gnu.org/software/libiconv/
  GNU gettext runtime (libintl)           LGPL-2.1-or-later
    https://www.gnu.org/software/gettext/
  ncurses (libncurses, libform, libmenu, libpanel, libtic)
                                          X11
    https://invisible-island.net/ncurses/ncurses-license.html
  libedit                                 BSD-3-Clause
    https://thrysoee.dk/editline/

  libstdc++                               GPL-3.0-or-later WITH GCC-exception-3.1
    Bundled so consumers link the same C++ runtime static-php-cli compiled
    ICU and libxml2 against. The GCC Runtime Library Exception permits
    linking it into a program under any license, provided the program is
    compiled with a compliant compiler. Read the exception before
    redistributing.
    https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html

INVENTORY
NOTICE_HEAD

for f in "$sdk_root"/lib/*; do
    [ -f "$f" ] || continue
    echo "  lib/$(basename "$f")" >> "$notices"
done

echo "==> wrote $notices"
